"""schema update

Revision ID: 2cbe21fb1edc
Revises: 
Create Date: 2025-09-12 21:03:53.301691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cbe21fb1edc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spending_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=50), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spending_table')
    # ### end Alembic commands ###
